### ISSUE TITLE
Hey chris, we met at the MISL internship and i now run a discord server for programmers

### ISSUE THREAD

**Issue by 70x72x69x76x61x74x65** [Chris-B33/Discord.py-Bot#1]
https://discord.gg/BSYrjqV
isacc, emmanuall, ciara, daniel are all there, hope to see you there soon!

**Comment by Chris-B33** [comment]
Hi! I lost motivation for a couple months and haven't been on here, but if you want to invite me again, I would appreciate it. :D

**Comment by 70x72x69x76x61x74x65** [comment]
https://discord.gg/ZwxSnyka7Y :)
